name: cozzinhe2
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.26.0
  cloud_firestore: ^4.4.2
  csv: ^6.0.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  flutter_rating_bar: ^4.0.1

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/cozzinheLogo.png
    - assets/images/img_user.png
    - assets/images/img_mifilter.svg
    - assets/images/img_search.svg
    - assets/images/cozzinheLogoCinza.png
    - assets/images/c1.png
    - assets/images/c2.png
    - assets/images/c3.png
    - assets/images/c4.png
    - assets/images/c5.png
    - assets/images/c6.png
    - assets/images/c7.png
    - assets/images/c8.png
    - assets/ingredientes.csv
